# Generated by Django 4.0.3 on 2022-04-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioProcessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiofile', models.FileField(upload_to='documents/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AudioProcessing.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('course', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('student_atnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AudioProcessing.student')),
            ],
        ),
    ]
