# Generated by Django 4.0.3 on 2022-04-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AudioProcessing', '0002_audio_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
