# Generated by Django 4.0.3 on 2022-04-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AudioProcessing', '0004_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
