# Generated by Django 4.0.3 on 2022-04-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AudioProcessing', '0006_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
